"""Increase ISBN length to 17

Revision ID: 21af2b254e31
Revises: 1feb7c482986
Create Date: 2024-08-18 23:49:56.176950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21af2b254e31'
down_revision = '1feb7c482986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('cover_image_url',
               existing_type=sa.VARCHAR(length=1255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('affiliate_link',
               existing_type=sa.VARCHAR(length=1255),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('affiliate_link',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1255),
               existing_nullable=True)
        batch_op.alter_column('cover_image_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1255),
               existing_nullable=True)
       

    # ### end Alembic commands ###
