"""Increase ISBN length to 17

Revision ID: e34e8aba8bbb
Revises: 21af2b254e31
Create Date: 2024-08-19 00:05:04.765892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34e8aba8bbb'
down_revision = '21af2b254e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('books_isbn_key', type_='unique')
        batch_op.drop_column('isbn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', sa.VARCHAR(length=17), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('books_isbn_key', ['isbn'])

    # ### end Alembic commands ###
